export type ApplicationErrorCode =
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "NODE_NOT_FOUND"
  | "NODE_VERSION_CONFLICT"
  | "NODE_ALREADY_SENSITIVE"
  | "SECURITY_ROOT_FORBIDDEN"
  | "SECURITY_DOMAIN_ALREADY_EXISTS"
  | "SECURITY_DOMAIN_ASSIGNMENT_REQUIRES_COMMAND"
  | "SECURITY_ROOT_REQUIRES_EMPTY_LEAF"
  | "SECURITY_DOMAIN_ID_IN_USE"
  | "SECURITY_DOMAIN_VERSION_CONFLICT"
  | "SECURITY_GRANT_VERSION_CONFLICT"
  | "SECURITY_DOMAIN_LAST_ADMINISTRATOR"
  | "SECURITY_GRANT_TARGET_INELIGIBLE"
  | "PROJECT_MEMBERSHIP_VERSION_CONFLICT"
  | "PROJECT_MEMBERSHIP_TRANSITION_INVALID"
  | "PROJECT_MEMBERSHIP_TARGET_INELIGIBLE"
  | "TASK_NOT_FOUND"
  | "PARENT_NODE_NOT_FOUND"
  | "INVALID_NODE_LEADER"
  | "NODE_LEADER_DIRECT_INSERT_FORBIDDEN"
  | "ROLE_SLOT_NOT_FOUND"
  | "ROLE_BINDING_VERSION_CONFLICT"
  | "INVALID_ROLE_BINDING_CANDIDATE"
  | "INVALID_ROLE_SLOT"
  | "ROLE_SLOT_TEMPLATE_VERSION_FROZEN"
  | "ROLE_SLOT_IMMUTABLE_CONFLICT"
  | "ROLE_BINDING_RECORD_CORRUPT"
  | "ROLE_SLOT_RECORD_CORRUPT"
  | "ROLE_SLOT_AUDIT_RECORD_CORRUPT"
  | "PROJECT_MISMATCH"
  | "MILESTONE_TASK_FORBIDDEN"
  | "TASK_ALREADY_EXISTS"
  | "TASK_VERSION_CONFLICT"
  | "TASK_SECURITY_OWNERSHIP_IMMUTABLE"
  | "TASK_ACTION_FORBIDDEN"
  | "TASK_REVIEW_CYCLE_NOT_FOUND"
  | "TASK_REJECTION_REASON_REQUIRED"
  | "TASK_REVIEW_NOT_REQUIRED"
  | "TASK_REVIEWER_LOCKED_DURING_REVIEW"
  | "TASK_REVIEWER_UNCHANGED"
  | "TASK_ASSIGNEE_LOCKED_DURING_REVIEW"
  | "TASK_ASSIGNEE_UNCHANGED"
  | "REVIEWER_REQUIRED"
  | "REVIEWER_NOT_ALLOWED"
  | "REVIEWER_NOT_ELIGIBLE"
  | "ASSIGNEE_NOT_ELIGIBLE"
  | "ASSIGNEE_REQUIRED"
  | "SECURITY_MIGRATION_IN_PROGRESS"
  | "SECURITY_MIGRATION_NOT_FOUND"
  | "SECURITY_MIGRATION_VERSION_CONFLICT"
  | "SECURITY_MIGRATION_BATCH_INVALID"
  | "SECURITY_MIGRATION_VERIFICATION_INVALID"
  | "SECURITY_MIGRATION_PLAN_INVALID"
  | "SECURITY_MIGRATION_PLAN_IMMUTABLE"
  | "SECURITY_MIGRATION_PROGRESS_INVALID"
  | "SECURITY_MIGRATION_PERSISTENCE_INCONSISTENT"
  | "SECURITY_MIGRATION_INVENTORY_INVALID"
  | "SECURITY_MIGRATION_OBJECT_NOT_ELIGIBLE"
  | "SECURITY_MIGRATION_COMMIT_INVALID"
  | "SECURITY_MIGRATION_CONVERGENCE_NOT_READY"
  | "SECURITY_MIGRATION_OUTBOUND_FENCE_ACTIVE"
  | "SECURITY_MIGRATION_INVENTORY_INCOMPLETE"
  | "SECURITY_MIGRATION_ROLLBACK_INVALID"
  | "SECURITY_MIGRATION_ROLLBACK_INCOMPLETE"
  | "SECURITY_MIGRATION_TERMINAL_BYPASS_FORBIDDEN"
  | "SECURITY_MIGRATION_MANIFEST_MISMATCH"
  | "SECURITY_MIGRATION_EVIDENCE_EXPIRED"
  | "SECURITY_MIGRATION_EVIDENCE_REPLAYED"
  | "SECURITY_MIGRATION_EVIDENCE_INVALID"
  | "SECURITY_MIGRATION_RECORD_CORRUPT"
  | "SECURITY_MIGRATION_EVIDENCE_NOT_FOUND"
  | "SECURITY_MIGRATION_EVIDENCE_NOT_VERIFIED"
  | "SECURITY_MIGRATION_EVIDENCE_REQUIRED"
  | "SECURITY_MIGRATION_MANIFEST_SNAPSHOT_NOT_FOUND"
  | "SECURITY_MIGRATION_EVIDENCE_ALREADY_VERIFIED"
  | "TASK_START_TRANSITION_INVALID"
  | "TASK_SUBMIT_TRANSITION_INVALID"
  | "TASK_ACCEPT_TRANSITION_INVALID"
  | "TASK_REJECT_TRANSITION_INVALID"
  | "TASK_WITHDRAW_TRANSITION_INVALID"
  | "TASK_DIRECT_COMPLETE_FORBIDDEN"
  | "TASK_IS_TERMINAL"
  | "ASSET_ALREADY_EXISTS"
  | "ASSET_SECURITY_OWNERSHIP_IMMUTABLE"
  | "IDEMPOTENCY_KEY_REQUIRED"
  | "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD"
  | "FILE_SIZE_INVALID"
  | "ASSET_CONTENT_HASH_MISMATCH"
  | "INVALID_JSON"
  | "REQUEST_TOO_LARGE"
  | "VALIDATION_FAILED"
  | "HULY_ADAPTER_NOT_CONFIGURED"
  | "UPSTREAM_FAILURE"
  | "CONFLICT"
  | "INTEGRATION_OPERATION_NOT_FOUND"
  | "INTEGRATION_OPERATION_VERSION_CONFLICT"
  | "INTEGRATION_OPERATION_NOT_RECOVERABLE"
  | "INTEGRATION_OPERATION_REQUIRES_SPECIALIZED_RECOVERY"
  | "INTEGRATION_RECOVERY_JOB_NOT_DEAD_LETTER"
  | "DELIVERABLE_NOT_FOUND"
  | "DELIVERABLE_ALREADY_EXISTS"
  | "DELIVERABLE_VERSION_CONFLICT"
  | "DELIVERABLE_SECURITY_OWNERSHIP_IMMUTABLE"
  | "DELIVERABLE_ACTION_FORBIDDEN"
  | "DELIVERABLE_SUBMISSION_FORBIDDEN"
  | "DELIVERABLE_ALREADY_SUBMITTED"
  | "DELIVERABLE_NOT_SUBMITTED"
  | "DELIVERABLE_IS_TERMINAL"
  | "DELIVERABLE_ALREADY_ACCEPTED"
  | "DELIVERABLE_ALREADY_WAIVED"
  | "DELIVERABLE_SUBMIT_TRANSITION_INVALID"
  | "DELIVERABLE_ACCEPT_TRANSITION_INVALID"
  | "DELIVERABLE_WAIVE_TRANSITION_INVALID"
  | "DELIVERABLE_RECORD_CORRUPT"
  | "EVIDENCE_NOT_FOUND"
  | "EVIDENCE_SCOPE_MISMATCH"
  | "EVIDENCE_NOT_AVAILABLE"
  | "PROCESS_RECORD_UNSUPPORTED"
  | "SOURCE_TYPE_UNSUPPORTED"
  | "INSUFFICIENT_EVIDENCE_COUNT"
  | "DUPLICATE_EVIDENCE"
  | "WAIVER_REASON_REQUIRED"
  | "PM_ROLE_REQUIRED"
  | "INVALID_DELIVERABLE_KEY";

export class ApplicationError extends Error {
  readonly code: ApplicationErrorCode;

  constructor(code: ApplicationErrorCode, message: string) {
    super(message);
    this.name = "ApplicationError";
    this.code = code;
  }
}

export function asApplicationError(error: unknown): ApplicationError {
  if (error instanceof ApplicationError) return error;
  if (error instanceof Error && knownCodes.has(error.message as ApplicationErrorCode)) {
    return new ApplicationError(error.message as ApplicationErrorCode, error.message);
  }
  if (error instanceof Error && error.message.startsWith("Aggregate already exists:")) {
    return new ApplicationError("CONFLICT", error.message);
  }
  if (error instanceof Error && (error.message.startsWith("INVALID_ROLE_SLOT_KEY:") || error.message.startsWith("INVALID_DELIVERABLE_KEY:") || error.message === "TASK_RECEIPT_INVALID")) {
    return new ApplicationError("VALIDATION_FAILED", error.message);
  }
  return new ApplicationError("UPSTREAM_FAILURE", error instanceof Error ? error.message : String(error));
}

const knownCodes = new Set<ApplicationErrorCode>([
  "UNAUTHORIZED",
  "FORBIDDEN",
  "NOT_FOUND",
  "NODE_NOT_FOUND",
  "NODE_VERSION_CONFLICT",
  "NODE_ALREADY_SENSITIVE",
  "SECURITY_ROOT_FORBIDDEN",
  "SECURITY_DOMAIN_ALREADY_EXISTS",
  "SECURITY_DOMAIN_ASSIGNMENT_REQUIRES_COMMAND",
  "SECURITY_ROOT_REQUIRES_EMPTY_LEAF",
  "SECURITY_DOMAIN_ID_IN_USE",
  "SECURITY_DOMAIN_VERSION_CONFLICT",
  "SECURITY_GRANT_VERSION_CONFLICT",
  "SECURITY_DOMAIN_LAST_ADMINISTRATOR",
  "SECURITY_GRANT_TARGET_INELIGIBLE",
  "PROJECT_MEMBERSHIP_VERSION_CONFLICT",
  "PROJECT_MEMBERSHIP_TRANSITION_INVALID",
  "PROJECT_MEMBERSHIP_TARGET_INELIGIBLE",
  "TASK_NOT_FOUND",
  "PARENT_NODE_NOT_FOUND",
  "INVALID_NODE_LEADER",
  "NODE_LEADER_DIRECT_INSERT_FORBIDDEN",
  "ROLE_SLOT_NOT_FOUND",
  "ROLE_BINDING_VERSION_CONFLICT",
  "INVALID_ROLE_BINDING_CANDIDATE",
  "INVALID_ROLE_SLOT",
  "ROLE_SLOT_TEMPLATE_VERSION_FROZEN",
  "ROLE_SLOT_IMMUTABLE_CONFLICT",
  "ROLE_BINDING_RECORD_CORRUPT",
  "ROLE_SLOT_RECORD_CORRUPT",
  "ROLE_SLOT_AUDIT_RECORD_CORRUPT",
  "PROJECT_MISMATCH",
  "MILESTONE_TASK_FORBIDDEN",
  "TASK_ALREADY_EXISTS",
  "TASK_VERSION_CONFLICT",
  "TASK_SECURITY_OWNERSHIP_IMMUTABLE",
  "TASK_ACTION_FORBIDDEN",
  "TASK_REVIEW_CYCLE_NOT_FOUND",
  "TASK_REJECTION_REASON_REQUIRED",
  "TASK_REVIEW_NOT_REQUIRED",
  "TASK_REVIEWER_LOCKED_DURING_REVIEW",
  "TASK_REVIEWER_UNCHANGED",
  "TASK_ASSIGNEE_LOCKED_DURING_REVIEW",
  "TASK_ASSIGNEE_UNCHANGED",
  "REVIEWER_REQUIRED",
  "REVIEWER_NOT_ALLOWED",
  "REVIEWER_NOT_ELIGIBLE",
  "ASSIGNEE_NOT_ELIGIBLE",
  "ASSIGNEE_REQUIRED",
  "SECURITY_MIGRATION_IN_PROGRESS",
  "SECURITY_MIGRATION_NOT_FOUND",
  "SECURITY_MIGRATION_VERSION_CONFLICT",
  "SECURITY_MIGRATION_BATCH_INVALID",
  "SECURITY_MIGRATION_VERIFICATION_INVALID",
  "SECURITY_MIGRATION_PLAN_INVALID",
  "SECURITY_MIGRATION_PLAN_IMMUTABLE",
  "SECURITY_MIGRATION_PROGRESS_INVALID",
  "SECURITY_MIGRATION_PERSISTENCE_INCONSISTENT",
  "SECURITY_MIGRATION_INVENTORY_INVALID",
  "SECURITY_MIGRATION_OBJECT_NOT_ELIGIBLE",
  "SECURITY_MIGRATION_COMMIT_INVALID",
  "SECURITY_MIGRATION_CONVERGENCE_NOT_READY",
  "SECURITY_MIGRATION_OUTBOUND_FENCE_ACTIVE",
  "SECURITY_MIGRATION_INVENTORY_INCOMPLETE",
  "SECURITY_MIGRATION_ROLLBACK_INVALID",
  "SECURITY_MIGRATION_ROLLBACK_INCOMPLETE",
  "SECURITY_MIGRATION_TERMINAL_BYPASS_FORBIDDEN",
  "SECURITY_MIGRATION_MANIFEST_MISMATCH",
  "SECURITY_MIGRATION_EVIDENCE_EXPIRED",
  "SECURITY_MIGRATION_EVIDENCE_REPLAYED",
  "SECURITY_MIGRATION_EVIDENCE_INVALID",
  "SECURITY_MIGRATION_RECORD_CORRUPT",
  "SECURITY_MIGRATION_EVIDENCE_NOT_FOUND",
  "SECURITY_MIGRATION_EVIDENCE_NOT_VERIFIED",
  "SECURITY_MIGRATION_EVIDENCE_REQUIRED",
  "SECURITY_MIGRATION_MANIFEST_SNAPSHOT_NOT_FOUND",
  "SECURITY_MIGRATION_EVIDENCE_ALREADY_VERIFIED",
  "TASK_START_TRANSITION_INVALID",
  "TASK_SUBMIT_TRANSITION_INVALID",
  "TASK_ACCEPT_TRANSITION_INVALID",
  "TASK_REJECT_TRANSITION_INVALID",
  "TASK_WITHDRAW_TRANSITION_INVALID",
  "TASK_DIRECT_COMPLETE_FORBIDDEN",
  "TASK_IS_TERMINAL",
  "ASSET_ALREADY_EXISTS",
  "ASSET_SECURITY_OWNERSHIP_IMMUTABLE",
  "IDEMPOTENCY_KEY_REQUIRED",
  "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD",
  "FILE_SIZE_INVALID",
  "ASSET_CONTENT_HASH_MISMATCH",
  "INVALID_JSON",
  "REQUEST_TOO_LARGE",
  "VALIDATION_FAILED",
  "HULY_ADAPTER_NOT_CONFIGURED",
  "UPSTREAM_FAILURE",
  "CONFLICT",
  "INTEGRATION_OPERATION_NOT_FOUND",
  "INTEGRATION_OPERATION_VERSION_CONFLICT",
  "INTEGRATION_OPERATION_NOT_RECOVERABLE",
  "INTEGRATION_OPERATION_REQUIRES_SPECIALIZED_RECOVERY",
  "INTEGRATION_RECOVERY_JOB_NOT_DEAD_LETTER",
  "DELIVERABLE_NOT_FOUND",
  "DELIVERABLE_ALREADY_EXISTS",
  "DELIVERABLE_VERSION_CONFLICT",
  "DELIVERABLE_SECURITY_OWNERSHIP_IMMUTABLE",
  "DELIVERABLE_ACTION_FORBIDDEN",
  "DELIVERABLE_SUBMISSION_FORBIDDEN",
  "DELIVERABLE_ALREADY_SUBMITTED",
  "DELIVERABLE_NOT_SUBMITTED",
  "DELIVERABLE_IS_TERMINAL",
  "DELIVERABLE_ALREADY_ACCEPTED",
  "DELIVERABLE_ALREADY_WAIVED",
  "DELIVERABLE_SUBMIT_TRANSITION_INVALID",
  "DELIVERABLE_ACCEPT_TRANSITION_INVALID",
  "DELIVERABLE_WAIVE_TRANSITION_INVALID",
  "DELIVERABLE_RECORD_CORRUPT",
  "EVIDENCE_NOT_FOUND",
  "EVIDENCE_SCOPE_MISMATCH",
  "EVIDENCE_NOT_AVAILABLE",
  "PROCESS_RECORD_UNSUPPORTED",
  "SOURCE_TYPE_UNSUPPORTED",
  "INSUFFICIENT_EVIDENCE_COUNT",
  "DUPLICATE_EVIDENCE",
  "WAIVER_REASON_REQUIRED",
  "PM_ROLE_REQUIRED",
  "INVALID_DELIVERABLE_KEY",
]);
