export type ApplicationErrorCode =
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "NODE_NOT_FOUND"
  | "NODE_VERSION_CONFLICT"
  | "NODE_ALREADY_SENSITIVE"
  | "SECURITY_ROOT_FORBIDDEN"
  | "SECURITY_DOMAIN_ALREADY_EXISTS"
  | "SECURITY_DOMAIN_ASSIGNMENT_REQUIRES_COMMAND"
  | "SECURITY_ROOT_REQUIRES_EMPTY_LEAF"
  | "SECURITY_DOMAIN_ID_IN_USE"
  | "TASK_NOT_FOUND"
  | "PARENT_NODE_NOT_FOUND"
  | "PROJECT_MISMATCH"
  | "MILESTONE_TASK_FORBIDDEN"
  | "TASK_ALREADY_EXISTS"
  | "TASK_VERSION_CONFLICT"
  | "TASK_ACTION_FORBIDDEN"
  | "TASK_REVIEW_CYCLE_NOT_FOUND"
  | "TASK_REJECTION_REASON_REQUIRED"
  | "TASK_REVIEW_NOT_REQUIRED"
  | "TASK_REVIEWER_LOCKED_DURING_REVIEW"
  | "TASK_REVIEWER_UNCHANGED"
  | "TASK_ASSIGNEE_LOCKED_DURING_REVIEW"
  | "TASK_ASSIGNEE_UNCHANGED"
  | "REVIEWER_REQUIRED"
  | "REVIEWER_NOT_ALLOWED"
  | "REVIEWER_NOT_ELIGIBLE"
  | "ASSIGNEE_NOT_ELIGIBLE"
  | "ASSIGNEE_REQUIRED"
  | "SECURITY_MIGRATION_IN_PROGRESS"
  | "TASK_START_TRANSITION_INVALID"
  | "TASK_SUBMIT_TRANSITION_INVALID"
  | "TASK_ACCEPT_TRANSITION_INVALID"
  | "TASK_REJECT_TRANSITION_INVALID"
  | "TASK_WITHDRAW_TRANSITION_INVALID"
  | "TASK_DIRECT_COMPLETE_FORBIDDEN"
  | "TASK_IS_TERMINAL"
  | "ASSET_ALREADY_EXISTS"
  | "IDEMPOTENCY_KEY_REQUIRED"
  | "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD"
  | "FILE_SIZE_INVALID"
  | "ASSET_CONTENT_HASH_MISMATCH"
  | "INVALID_JSON"
  | "REQUEST_TOO_LARGE"
  | "VALIDATION_FAILED"
  | "HULY_ADAPTER_NOT_CONFIGURED"
  | "UPSTREAM_FAILURE"
  | "CONFLICT"
  | "INTEGRATION_OPERATION_NOT_FOUND"
  | "INTEGRATION_OPERATION_VERSION_CONFLICT"
  | "INTEGRATION_OPERATION_NOT_RECOVERABLE"
  | "INTEGRATION_OPERATION_REQUIRES_SPECIALIZED_RECOVERY"
  | "INTEGRATION_RECOVERY_JOB_NOT_DEAD_LETTER";

export class ApplicationError extends Error {
  readonly code: ApplicationErrorCode;

  constructor(code: ApplicationErrorCode, message: string) {
    super(message);
    this.name = "ApplicationError";
    this.code = code;
  }
}

export function asApplicationError(error: unknown): ApplicationError {
  if (error instanceof ApplicationError) return error;
  if (error instanceof Error && knownCodes.has(error.message as ApplicationErrorCode)) {
    return new ApplicationError(error.message as ApplicationErrorCode, error.message);
  }
  if (error instanceof Error && error.message.startsWith("Aggregate already exists:")) {
    return new ApplicationError("CONFLICT", error.message);
  }
  return new ApplicationError("UPSTREAM_FAILURE", error instanceof Error ? error.message : String(error));
}

const knownCodes = new Set<ApplicationErrorCode>([
  "UNAUTHORIZED",
  "FORBIDDEN",
  "NOT_FOUND",
  "NODE_NOT_FOUND",
  "NODE_VERSION_CONFLICT",
  "NODE_ALREADY_SENSITIVE",
  "SECURITY_ROOT_FORBIDDEN",
  "SECURITY_DOMAIN_ALREADY_EXISTS",
  "SECURITY_DOMAIN_ASSIGNMENT_REQUIRES_COMMAND",
  "SECURITY_ROOT_REQUIRES_EMPTY_LEAF",
  "SECURITY_DOMAIN_ID_IN_USE",
  "TASK_NOT_FOUND",
  "PARENT_NODE_NOT_FOUND",
  "PROJECT_MISMATCH",
  "MILESTONE_TASK_FORBIDDEN",
  "TASK_ALREADY_EXISTS",
  "TASK_VERSION_CONFLICT",
  "TASK_ACTION_FORBIDDEN",
  "TASK_REVIEW_CYCLE_NOT_FOUND",
  "TASK_REJECTION_REASON_REQUIRED",
  "TASK_REVIEW_NOT_REQUIRED",
  "TASK_REVIEWER_LOCKED_DURING_REVIEW",
  "TASK_REVIEWER_UNCHANGED",
  "TASK_ASSIGNEE_LOCKED_DURING_REVIEW",
  "TASK_ASSIGNEE_UNCHANGED",
  "REVIEWER_REQUIRED",
  "REVIEWER_NOT_ALLOWED",
  "REVIEWER_NOT_ELIGIBLE",
  "ASSIGNEE_NOT_ELIGIBLE",
  "ASSIGNEE_REQUIRED",
  "SECURITY_MIGRATION_IN_PROGRESS",
  "TASK_START_TRANSITION_INVALID",
  "TASK_SUBMIT_TRANSITION_INVALID",
  "TASK_ACCEPT_TRANSITION_INVALID",
  "TASK_REJECT_TRANSITION_INVALID",
  "TASK_WITHDRAW_TRANSITION_INVALID",
  "TASK_DIRECT_COMPLETE_FORBIDDEN",
  "TASK_IS_TERMINAL",
  "ASSET_ALREADY_EXISTS",
  "IDEMPOTENCY_KEY_REQUIRED",
  "IDEMPOTENCY_KEY_REUSED_WITH_DIFFERENT_PAYLOAD",
  "FILE_SIZE_INVALID",
  "ASSET_CONTENT_HASH_MISMATCH",
  "INVALID_JSON",
  "REQUEST_TOO_LARGE",
  "VALIDATION_FAILED",
  "HULY_ADAPTER_NOT_CONFIGURED",
  "UPSTREAM_FAILURE",
  "CONFLICT",
  "INTEGRATION_OPERATION_NOT_FOUND",
  "INTEGRATION_OPERATION_VERSION_CONFLICT",
  "INTEGRATION_OPERATION_NOT_RECOVERABLE",
  "INTEGRATION_OPERATION_REQUIRES_SPECIALIZED_RECOVERY",
  "INTEGRATION_RECOVERY_JOB_NOT_DEAD_LETTER",
]);
